import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PromoNav from "./components/PromoNav";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FooterSecondary from "./components/FooterSecondary";

const inter = Inter({
	subsets: ["latin"],
	weight: ["300", "500", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<PromoNav />
				<main className="mx-auto max-w-7xl bg-white container">
					<Navbar />
					{children}
				</main>
				<Footer />
				<FooterSecondary />
			</body>
		</html>
	);
}
